name: Backend CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'Backend/**'
      - '.github/workflows/backendPipeline.yml'

jobs:
  build-and-push:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker hub
        uses: docker/login-action@v2
        with:
          username: 
          password:

      - name: Build and push docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: yourdockerhubusername/backend:latest
