name: Backend CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - "Backend/**"
      - ".github/workflows/backendPipeline.yml"

jobs:
  build-and-deploy:
    name: "Build, push Docker image & deploy to Cloud Run"
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: "Checkout Code"
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker buildx
      - name: "Set up Docker buildx"
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Authenticate with GCP
      - name: "Authenticate to GCP"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 4️⃣ Configure Docker for Artifact Registry
      - name: "Configure Docker for Artifact Registry"
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      # 5️⃣ Clean Docker builder cache (prevents digest errors)
      - name: "Clean Docker builder cache"
        run: docker builder prune -af

      # 6️⃣ Build & push Docker image (no cache-from to avoid digest errors)
      - name: "Build & Push Docker Image"
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          push: true
          tags: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend-repo/backend:latest
          no-cache: true

      # 7️⃣ Deploy to Cloud Run
      - name: "Deploy to Cloud Run"
        run: |
          gcloud run deploy backend-service \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend-repo/backend:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars PORT=8080,\
            ORIGIN=${{ secrets.ORIGIN }},\
            MONGODB=${{ secrets.MONGODB }},\
            NODEMAILER_EMAIL=${{ secrets.NODEMAILER_EMAIL }},\
            NODEMAILER_PASSWORD=${{ secrets.NODEMAILER_PASSWORD }},\
            ACCESSTOKEN_SECRET_KEY=${{ secrets.ACCESSTOKEN_SECRET_KEY }},\
            REFRESHTOKEN_SECRET_KEY=${{ secrets.REFRESHTOKEN_SECRET_KEY }},\
            STRIPE_PK=${{ secrets.STRIPE_PK }},\
            STRIPE_SK=${{ secrets.STRIPE_SK }},\
            REDIS_URL=${{ secrets.REDIS_URL }},\
            RAZORPAY_SECRET=${{ secrets.RAZORPAY_SECRET }},\
            RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }},\
            ADMIN_ID=${{ secrets.ADMIN_ID }},\
            HOSTNAME=${{ secrets.HOSTNAME }},\
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }},\
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }},\
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }},\
            CLOUDINARY_PREFIX=${{ secrets.CLOUDINARY_PREFIX }}
